# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
parameters:
- name: host
  displayName: API Manager Hostname
  type: string
  default: localhost
- name: username
  displayName: API Manager Username
  type: string
  default: apiadmin
- name: password
  displayName: API Manager Password
  type: string
  default: changeme
- name: returnCodeMapping
  displayName: CLI Return code mapping
  type: string
  default: 10:0
  
pool:
  vmImage: 'ubuntu-latest'
    
trigger:
- master

jobs:
- job: deploy
  displayName: Deploy API to Axway API manager
  
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean exec:java'
      options: '-Dexec.args="-h ${{ parameters.host }} -u ${{ parameters.username }} -p ${{ parameters.password }} -c ./api-definition/1-design-only-config.json -s api-env -f true -returnCodeMapping ${{ parameters.returnCodeMapping }}"'
- job: test
  displayName: Test API 
  
  steps:
  - task: NodeTool@0
  - script: npm install newman
   
